CREATE USER EXAMEN
IDENTIFIED BY EXAMEN DEFAULT TABLESPACE users;
GRANT CONNECT TO EXAMEN;
GRANT RESOURCE TO EXAMEN;



CREATE TABLE CLIENTES(
    CODIGO     NUMBER(10),
    DIRECCION  VARCHAR2(50),
    TELEFONO   NUMBER(10),
CONSTRAINT PK_CLIENTES PRIMARY KEY (CODIGO)
);
COMMIT;

CREATE TABLE PROYECTOS(
    CODIGO      NUMBER(10),
    DESCRIPCION VARCHAR2(50) CONSTRAINT DESC_OBLI NOT NULL, --RESTRICION DE LA DESCRIPCION DEL PROYECTO NO PUEDE SER NULO RESTRICCION NUMERO3
    CUANTIA     VARCHAR2(20),
    FECHAINICIO DATE,
    FECHAFIN    DATE,
    CODIGOCLIENTE NUMBER(10),
CONSTRAINT PK_PROYECTOS PRIMARY KEY (CODIGO),
CONSTRAINT FK_PROYECTOS FOREIGN KEY (CODIGOCLIENTE) REFERENCES CLIENTES(CODIGO)
);

COMMIT;

CREATE TABLE COLABORADORES(
    NIF     VARCHAR2(9) ,
    NOMBRE  VARCHAR2(20),
    APELLIDOS VARCHAR2(20),
    DOMICILIO VARCHAR2(50),
    TELEFONO  NUMBER(10),
    BANCO     VARCHAR2(20),
    NUMEROCUENTA NUMBER(10),
CONSTRAINT PK_COLABORADORES PRIMARY KEY (NIF)
);

COMMIT;

CREATE TABLE COLABORACIONES(
    CODIGOPROYECTO NUMBER(10),
    NIFCOLABORADOR VARCHAR2(9),
CONSTRAINT FK_COLABORACIONES_1 FOREIGN KEY (CODIGOPROYECTO) REFERENCES PROYECTOS(CODIGO),
CONSTRAINT FK_COLABORACIONES_2 FOREIGN KEY (NIFCOLABORADOR) REFERENCES COLABORADORES(NIF)
);

COMMIT;

CREATE TABLE TIPOS_PAGO(
    CODIGO      NUMBER(10),
    DESCRIPCION VARCHAR(50), 
CONSTRAINT PK_TIPOPAGO PRIMARY KEY (CODIGO),
CONSTRAINT TIPOS_PAGO  CHECK (DESCRIPCION IN ('CONTADO', 'TRANSFERENCIA', 'LETRAS')) --EL TIPO DE PAGO SERA CONTADOR, TRANSFERENCIA O LETRAS ES LA RESTRICCION 1
);

COMMIT;

CREATE TABLE PAGOS(
    NUMERO     NUMBER(10),
    CONCEPTO   VARCHAR2(20),
    IMPORTE    NUMBER(10),
    FECHA      DATE,
    CODIGOTIPODEPAGO    NUMBER(10),
    CODIGOPROYECTO      NUMBER(10),
    NIFCOLABORADOR      VARCHAR2(9),
CONSTRAINT PK_PAGOS PRIMARY KEY (NUMERO),
CONSTRAINT FK_PAGOS_1 FOREIGN KEY (CODIGOTIPODEPAGO) REFERENCES TIPOS_PAGO(CODIGO),
CONSTRAINT FK_PAGOS_2 FOREIGN KEY (CODIGOPROYECTO) REFERENCES PROYECTOS(CODIGO),
CONSTRAINT FK_PAGOS_3 FOREIGN KEY (NIFCOLABORADOR) REFERENCES COLABORADORES(NIF)
);

COMMIT;




ALTER TABLE PROYECTOS --8. AÑADE LA COLUMNA NOMBRE EN LA TABLA PROYECTO
    ADD (
        NOMBRE  VARCHAR2(20)
    );

COMMIT;