CREATE TABLE PERSONAL
(
    PASAPORTE    VARCHAR2(10),
    NOMBRE       VARCHAR2(20),
    TELEFONO     NUMBER(10),
    DIRECCION    VARCHAR2(20),
    ANTIGUEDAD   DATE,
    HORAS_EXTRAS NUMBER(2),
    TIPOS        VARCHAR2(10),
 CONSTRAINT TIPOS CHECK (PERSONAL IN  ('VIA LACTEA','ANDROMEDA','SOMBRERO')),
 CONSTRAINT PK_PERSONAL PRIMARY KEY(PASAPORTE)
);
COMMIT;

CREATE TABLE AUXILIARES
(
    PASAPORTE_AUXILIARES    VARCHAR2(10),
    NOMBRE       VARCHAR2(20),
    TELEFONO     NUMBER(10),
    DIRECCION    VARCHAR2(20),
    ANTIGUEDAD   DATE,
    HORAS_EXTRAS NUMBER(2),
    CONSTRAINT PK_AUXILIARES PRIMARY KEY(PASAPORTE_AUXILIARES)
);
COMMIT;

CREATE TABLE VUELOS
(
    COMPAÑIA    VARCHAR2(20),
    VUELO       VARCHAR2(10),
    ORIGEN      VARCHAR2(20),
    DESTINO     VARCHAR2(20),
    HORARIO     TIME,
    PASAPORTE_PILOTOS  VARCHAR2(10),
    PASAPORTE_COPILOS  VARCHAR2(10),
    CONSTRAINT PK_VUELOS PRIMARY KEY (COMPAÑIA, VUELO, ORIGEN)
);
COMMIT;

CREATE TABLE AUXILIA
(
    FECHA       DATE,
    COMPAÑIA_VUELOS    VARCHAR2(20),
    VUELO_VUELOS       VARCHAR2(10),
    ORIGEN_VUELOS      VARCHAR2(20),
    PASAPORTE_AUXILIARES    VARCHAR2(10),
    CONSTRAINT PK_AUXILIAR PRIMARY KEY(FECHA),
    CONSTRAINT FK_COMPAÑIA FOREIGN KEY (COMPAÑIA_VUELOS) REFERENCES VUELOS (COMPAÑIA),
    CONSTRAINT FK_VUELOS FOREIGN KEY (VUELO_VUELOS) REFERENCES VUELOS (VUELO),
    CONSTRAINT FK_ORIGEN FOREIGN KEY (ORIGEN_VUELOS) REFERENCES VUELOS (ORIGEN),
    CONSTRAINT FK_PASAPORTE FOREIGN KEY (PASAPORTE_AUXILIARES) REFERENCES AUXILIARES (PASAPORTE_AUXILIARES),
);
COMMIT;

CREATE TABLE PASAJEROS
(
    PASAPORTE_PASAJEROS     VARCHAR2(10),
    NOMBRE        VARCHAR2(10),
    CONSTRAINT PK_PASAJEROS PRIMARY KEY(PASAPORTE_PASAJEROS)
);
COMMIT;


