CREATE TABLE PERSONAL
(
    PASAPORTE    VARCHAR2(10),
    NOMBRE       VARCHAR2(20),
    TELEFONO     NUMBER(10),
    DIRECCION    VARCHAR2(20),
    ANTIGUEDAD   DATE,
    HORAS_EXTRAS NUMBER(2),
    TIPOS        VARCHAR2(10),
 CONSTRAINT TIPOS CHECK (PERSONAL IN  ('VIA LACTEA','ANDROMEDA','SOMBRERO')),
 CONSTRAINT PK_PERSONAL PRIMARY KEY(PASAPORTE)
);
COMMIT;

CREATE TABLE AUXILIARES
(
    PASAPORTE_AUXILIARES    VARCHAR2(10),
    NOMBRE       VARCHAR2(20),
    TELEFONO     NUMBER(10),
    DIRECCION    VARCHAR2(20),
    ANTIGUEDAD   DATE,
    HORAS_EXTRAS NUMBER(2),
    CONSTRAINT PK_AUXILIARES PRIMARY KEY(PASAPORTE_AUXILIARES)
);
COMMIT;

CREATE TABLE AEROPUERTO
(
    NOMBRE      VARCHAR2(20),
    DIRECCION   VARCHAR2(20),
    TELEFONO    NUMBER(10),
    DIRECTOR    VARCHAR2(10),
    NUM_PISTAS  NUMBER(10),
    VOLUMEN_TRAFICO VARCHAR2(10),
    CIUDAD_CERCANO  VARCHAR2(20),
    CONSTRAINT PK_NOMBRE_AEROPUERTO PRIMARY KEY(NOMBRE)

);
COMMIT;

CREATE TABLE VUELOS
(
    COMPAÑIA    VARCHAR2(20),
    VUELO       VARCHAR2(10),
    ORIGEN      VARCHAR2(20),
    DESTINO     VARCHAR2(20),
    HORARIO     TIME,
    PASAPORTE_PILOTOS  VARCHAR2(10),
    PASAPORTE_COPILOS  VARCHAR2(10),
    NOMBRE_AEROPUERTO   VARCHAR2(10),
    CONSTRAINT PK_VUELOS PRIMARY KEY (COMPAÑIA, VUELO, ORIGEN),
    CONSTRAINT FK_NOMBRE_AE FOREIGN KEY (NOMBRE_AEROPUERTO) REFERENCES AEROPUERTO (NOMBRE)
);
COMMIT;

CREATE TABLE AUXILIA
(
    FECHA       DATE,
    COMPAÑIA_VUELOS    VARCHAR2(20),
    VUELO_VUELOS       VARCHAR2(10),
    ORIGEN_VUELOS      VARCHAR2(20),
    PASAPORTE_AUXILIARES    VARCHAR2(10),
    CONSTRAINT PK_AUXILIAR PRIMARY KEY(FECHA),
    CONSTRAINT FK_COMPAÑIA FOREIGN KEY (COMPAÑIA_VUELOS) REFERENCES VUELOS (COMPAÑIA),
    CONSTRAINT FK_VUELOS FOREIGN KEY (VUELO_VUELOS) REFERENCES VUELOS (VUELO),
    CONSTRAINT FK_ORIGEN FOREIGN KEY (ORIGEN_VUELOS) REFERENCES VUELOS (ORIGEN),
    CONSTRAINT FK_PASAPORTE FOREIGN KEY (PASAPORTE_AUXILIARES) REFERENCES AUXILIARES (PASAPORTE_AUXILIARES),
);
COMMIT;

CREATE TABLE PASAJEROS
(
    PASAPORTE_PASAJEROS     VARCHAR2(10),
    NOMBRE        VARCHAR2(10),
    CONSTRAINT PK_PASAJEROS PRIMARY KEY(PASAPORTE_PASAJEROS)
);
COMMIT;

CREATE TABLE TOMAN
(
    FECHA               DATE,
    NUM_BULTOS          NUMBER(10),
    PESO_EQUIPAJE       NUMBER(10),
    PASAPORTE_PASAJEROS VARCHAR(10),
   COMPAÑIA_VUELOS    VARCHAR2(20),
    VUELO_VUELOS       VARCHAR2(10),
    ORIGEN_VUELOS      VARCHAR2(20), 
    CONSTRAINT PK_TOMAN PRIMARY KEY(FECHA),
    CONSTRAINT FK_COMPAÑIA FOREIGN KEY (COMPAÑIA_VUELOS) REFERENCES VUELOS (COMPAÑIA),
    CONSTRAINT FK_VUELOS FOREIGN KEY (VUELO_VUELOS) REFERENCES VUELOS (VUELO),
    CONSTRAINT FK_ORIGEN FOREIGN KEY (ORIGEN_VUELOS) REFERENCES VUELOS (ORIGEN),
    CONSTRAINT FK_PASAPORTE_PASAJERO FOREIGN KEY (PASAPORTE_PASAJEROS) REFERENCES PASAJEROS (PASAPORTE_PASAJEROS)
);
COMMIT;

CREATE TABLE COMPAÑIA
(
    CODIGO      NUMBER(10),
    NOMBRE      VARCHAR2(15),
    CONSTRAINT PK_COMPAÑIA PRIMARY KEY(CODIGO)
);

COMMIT;

CREATE TABLE AVIONES
(
    NUM_SERIE       NUMBER(10),
    ANTIGUEDAD      VARCHAR2(15),
    HORAS_VUELO     TIME,
    CARACTERISTICA  VARCHAR2(30),
    CODIGO_COMPAÑIA NUMBER(10),
    FECHA_OPERAN     DATE,
     CONSTRAINT PK_AVIONES PRIMARY KEY(NUM_SERIE, FECHA_OPERAN),
     CONSTRAINT FK_AVIONES FOREIGN KEY (CODIGO_COMPAÑIA) REFERENCES COMPAÑIA (CODIGO)
);

COMMIT;