CREATE TABLE    PINACOTECAS
(ID_PINACOTECA       NUMBER(9), 
NOMBRE              VARCHAR2(25),
DIRECCION           VARCHAR2(50),
CIUDAD              VARCHAR2(20),
PAIS                VARCHAR2(30),
SUPERFICIE          NUMBER(10),
CONSTRAINT PK_PINACOTECAS PRIMARY KEY(ID_PINACOTECA)
);

COMMIT;

CREATE TABLE  CUADROS
(ID_CUADRO    NUMBER(10),  
N_CUADRO      VARCHAR2(30),
ANCHO         NUMBER(5),
ALTO          NUMBER(5),
F_PINTADO     DATE,
TECNICA       VARCHAR2(15),
FK_PINAC      NUMBER(10),
CONSTRAINT PK_CUADROS PRIMARY KEY(ID_CUADRO),
CONSTRAINT FK_PINAC FOREIGN KEY(FK_PINAC) REFERENCES PINACOTECAS
);

COMMIT;

CREATE TABLE PINTORES
(
    ID_PINTOR   NUMBER(9),
    N_PINTOR     VARCHAR2(30),
    CIUDAD       VARCHAR2(20),
    PAIS         VARCHAR2(20),
    FECHA_N      DATE,
    FECHA_F      DATE,
CONSTRAINT PK_PINTORES PRIMARY KEY(ID_PINTOR)
);

COMMIT;

CREATE TABLE CUADROS_PINTORES
(
    ID_FK_CUADRO   NUMBER(10),
    FK_PINTOR      NUMBER(10),
CONSTRAINT PK_CUADROS_PINTORES PRIMARY KEY(ID_FK_CUADRO),
CONSTRAINT FK1_CUADROS_CP FOREIGN KEY(ID_FK_CUADRO) REFERENCES CUADROS,
CONSTRAINT FK2_CUADROS_CP FOREIGN KEY(FK_PINTOR) REFERENCES PINTORES 
)

COMMIT;

CREATE TABLE ESCUELAS
(
    ID_ESCUELAS   NUMBER(10),
    N_ESCUELA     VARCHAR2(20),
    PAIS          VARCHAR2(20),
    FECHA_APAR    DATE,
CONSTRAINT PK_ESCUELAS PRIMARY KEY(ID_ESCUELAS),
)

COMMIT;

CREATE TABLE MECENAS
(
    ID_MECENAS     NUMBER(10),
    N_MECENAS      VARCHAR2(15),
    CIUDAD_NAC     VARCHAR2(20),
    PAIS           VARCHAR2(15),
CONSTRAINT PK_MECENAS PRIMARY KEY(ID_MECENAS)
)

COMMIT;

CREATE TABLE PINTORES_ESCUELAS
(
    ID_FK_PINTOR     NUMBER(10),
    FK_ESCUELA       NUMBER(10),
CONSTRAINT PK_PINTORES_ESCUELAS PRIMARY KEY(ID_FK_PINTOR),
CONSTRAINT FK1_PINTORES_PE FOREIGN KEY(ID_FK_PINTOR) REFERENCES PINTORES,
CONSTRAINT FK2_PINTORES_PE FOREIGN KEY(FK_ESCUELA) REFERENCES ESCUELAS 
)

COMMIT;

CREATE TABLE MAESTROS
(
    ID_FK_PINTOR   NUMBER(10),
    FK_MAESTRO     NUMBER(10),
CONSTRAINT PK_MAESTROS PRIMARY KEY(ID_FK_PINTOR),
CONSTRAINT FK1_MAESTROS FOREIGN KEY(ID_FK_PINTOR) REFERENCES PINTORES,
CONSTRAINT FK2_MAESTROS FOREIGN KEY(FK_MAESTRO) REFERENCES PINTORES
)

COMMIT;

CREATE TABLE MECENAZGO
(
    ID_FK_PINTOR   NUMBER(10),
    ID_FK_MECENAS  NUMBER(10),
    ID_FECHA_INCIO DATE,
    FECHA_FINAL    DATE,
);
COMMIT;